Bluron: forest_utils.c File Reference
forest_utils.c File Reference
Holds all forest related functions. Allows to go through the forest and change each cell to the next state with easy to understand interface.
#include "forest_utils.h"
Functions
errors_e update_forest_status (char *p_forest_string_char, const uint32_t u_forest_size)
update_forest_status takes the current forest state and updates it –inplace– according to the following logic:
void debug_forest_print (const char *const p_forest_string_char, const uint32_t u_forest_size)
print a forest when in debug mode
static char modify_cell (const uint32_t u_cell_idx, const uint32_t u_forest_size, const char *p_forest_string_char)
modify_cell Takes a cell in a given forest, and return the next state of this cell.
static char left_neighbor (const uint32_t u_cell_idx, const uint32_t u_forest_size, const char *p_forest_string_char)
left_neighbor returns the value of the left neighbor in a given forest string. If the cell has no such neighbors, i.e. it is the left most column of the tree, returns a value of 0.
static char right_neighbor (const uint32_t u_cell_idx, const uint32_t u_forest_size, const char *p_forest_string_char)
right_neighbor returns the value of the right neighbor in a given forest string. If the cell has no such neighbors, i.e. it is the right most column of the tree, returns a value of 0.
static char upper_neighbor (const uint32_t u_cell_idx, const uint32_t u_forest_size, const char *p_forest_string_char)
upper_neighbor returns the value of the upper neighbor in a given forest string. If the cell has no such neighbors, i.e. it is the upper most row of the tree, returns a value of 0.
static char lower_neighbor (const uint32_t u_cell_idx, const uint32_t u_forest_size, const char *p_forest_string_char)
lower_neighbor returns the value of the lower neighbor in a given forest string. If the cell has no such neighbors, i.e. it is the lower most row of the tree, returns a value of 0.
static char upper_left_neighbor (const uint32_t u_cell_idx, const uint32_t u_forest_size, const char *p_forest_string_char)
static char upper_right_neighbor (const uint32_t u_cell_idx, const uint32_t u_forest_size, const char *p_forest_string_char)
static char lower_left_neighbor (const uint32_t u_cell_idx, const uint32_t u_forest_size, const char *p_forest_string_char)
static char lower_right_neighbor (const uint32_t u_cell_idx, const uint32_t u_forest_size, const char *p_forest_string_char)
Detailed Description
Holds all forest related functions. Allows to go through the forest and change each cell to the next state with easy to understand interface.
Author
Matan Levy (levym.nosp@m.atan.nosp@m.levy@.nosp@m.gmai.nosp@m.l.com)
Version
0.1
Date
2020-11-03
Copyright
Copyright (c) 2020
Definition in file forest_utils.c.
Function Documentation
debug_forest_print()
void debug_forest_print (const char *const p_forest_string_char, const uint32_t u_forest_size)
print a forest when in debug mode
Parameters
p_forest_string_char
u_forest_size
Definition at line 82 of file forest_utils.c.
 {
     debug_print(SEPERATOR_LINE_STRING);
     for(uint32_t u_row_idx = 0; u_row_idx < u_forest_size; u_row_idx++)
     {
         for(uint32_t u_col_idx = 0; u_col_idx < u_forest_size; u_col_idx++)
         {
             debug_print("%c ", p_forest_string_char[u_forest_size*u_row_idx + u_col_idx]);
         }
         debug_print("\n");
     }
     debug_print(SEPERATOR_LINE_STRING);
 }
References debug_print, and SEPERATOR_LINE_STRING.
Referenced by update_forest_status().
left_neighbor()
static char left_neighbor (const uint32_t u_cell_idx, const uint32_t u_forest_size, const char * p_forest_string_char) static
left_neighbor returns the value of the left neighbor in a given forest string. If the cell has no such neighbors, i.e. it is the left most column of the tree, returns a value of 0.
Parameters
u_cell_idx
u_forest_size
p_forest_string_char
Returns
char
Definition at line 170 of file forest_utils.c.
 {
     char u_neighbor_val;
     if((u_cell_idx % u_forest_size) == 0)
     {
         u_neighbor_val = 0;
     }
     else
     {
         u_neighbor_val = p_forest_string_char[u_cell_idx-1];
     }
     return u_neighbor_val;
 }
Referenced by modify_cell().
lower_left_neighbor()
static char lower_left_neighbor (const uint32_t u_cell_idx, const uint32_t u_forest_size, const char * p_forest_string_char) static
Parameters
u_cell_idx
u_forest_size
p_forest_string_char
Returns
char
Definition at line 308 of file forest_utils.c.
 {
     char u_neighbor_val;
     if(((u_cell_idx + u_forest_size) > (u_forest_size * u_forest_size - 1)) || ((u_cell_idx % u_forest_size) == 0))
     {
         u_neighbor_val = 0;
     }
     else
     {
         u_neighbor_val = p_forest_string_char[u_cell_idx + u_forest_size - 1];
     }
     return u_neighbor_val;
 }
Referenced by modify_cell().
lower_neighbor()
static char lower_neighbor (const uint32_t u_cell_idx, const uint32_t u_forest_size, const char * p_forest_string_char) static
lower_neighbor returns the value of the lower neighbor in a given forest string. If the cell has no such neighbors, i.e. it is the lower most row of the tree, returns a value of 0.
Parameters
u_cell_idx
u_forest_size
p_forest_string_char
Returns
char
Definition at line 242 of file forest_utils.c.
 {
     char u_neighbor_val;
     if((u_cell_idx + u_forest_size) > (u_forest_size * u_forest_size - 1))
     {
         u_neighbor_val = 0;
     }
     else
     {
         u_neighbor_val = p_forest_string_char[u_cell_idx + u_forest_size];
     }
     return u_neighbor_val;
 }
Referenced by modify_cell().
lower_right_neighbor()
static char lower_right_neighbor (const uint32_t u_cell_idx, const uint32_t u_forest_size, const char * p_forest_string_char) static
Parameters
u_cell_idx
u_forest_size
p_forest_string_char
Returns
char
Definition at line 330 of file forest_utils.c.
 {
     char u_neighbor_val;
     if(((u_cell_idx + u_forest_size) > (u_forest_size * u_forest_size - 1)) || ((u_cell_idx % u_forest_size) == (u_forest_size - 1)))
     {
         u_neighbor_val = 0;
     }
     else
     {
         u_neighbor_val = p_forest_string_char[u_cell_idx + u_forest_size + 1];
     }
     return u_neighbor_val;
 }
Referenced by modify_cell().
modify_cell()
static char modify_cell (const uint32_t u_cell_idx, const uint32_t u_forest_size, const char * p_forest_string_char) static
modify_cell Takes a cell in a given forest, and return the next state of this cell.
Parameters
u_cell_idx
u_forest_size
p_forest_string_char
Returns
char
Definition at line 107 of file forest_utils.c.
 {
     const char u_current_cell = p_forest_string_char[u_cell_idx];
     char u_new_val = '\0';
     switch (u_current_cell)
     {
     case FIRE:
         u_new_val = GROUND;
         break;
     case TREE:
         // If a Tree as atleast one neighboring Fire, then it's new state should be Fire, else remains tree
         if(left_neighbor(u_cell_idx, u_forest_size, p_forest_string_char)  == FIRE ||
            upper_neighbor(u_cell_idx, u_forest_size, p_forest_string_char) == FIRE ||
            right_neighbor(u_cell_idx, u_forest_size, p_forest_string_char) == FIRE ||
            lower_neighbor(u_cell_idx, u_forest_size, p_forest_string_char) == FIRE    )
         {
             u_new_val = FIRE;
         }
         else // This is redundent but easier to read
         {
             u_new_val = TREE;
         }
         break;
     case GROUND:
         // If a Ground has atleast two neighboring Trees, then it's new state should be Tree, else remains Ground
         if(  ( (left_neighbor(u_cell_idx, u_forest_size, p_forest_string_char)  == TREE) +
                (right_neighbor(u_cell_idx, u_forest_size, p_forest_string_char)  == TREE) +
                (upper_neighbor(u_cell_idx, u_forest_size, p_forest_string_char)  == TREE) +
                (lower_neighbor(u_cell_idx, u_forest_size, p_forest_string_char)  == TREE) +
                (lower_left_neighbor(u_cell_idx, u_forest_size, p_forest_string_char)  == TREE) +
                (upper_left_neighbor(u_cell_idx, u_forest_size, p_forest_string_char)  == TREE) +
                (upper_right_neighbor(u_cell_idx, u_forest_size, p_forest_string_char)  == TREE) +
                (lower_right_neighbor(u_cell_idx, u_forest_size, p_forest_string_char)  == TREE)   ) >= FATHER_TREES_THRESHOLD )
         {
             u_new_val = TREE;
         }
         else // This is redundent but easier to read
         {
             u_new_val = GROUND;
         }
         break;
     default:
         printf("INVALID char input in forest string. file: %s, line: %d\n", __FILE__, __LINE__);
         break;
     }
     return u_new_val;
 }
References FATHER_TREES_THRESHOLD, FIRE, GROUND, left_neighbor(), lower_left_neighbor(), lower_neighbor(), lower_right_neighbor(), right_neighbor(), TREE, upper_left_neighbor(), upper_neighbor(), and upper_right_neighbor().
Referenced by update_forest_status().
right_neighbor()
static char right_neighbor (const uint32_t u_cell_idx, const uint32_t u_forest_size, const char * p_forest_string_char) static
right_neighbor returns the value of the right neighbor in a given forest string. If the cell has no such neighbors, i.e. it is the right most column of the tree, returns a value of 0.
Parameters
u_cell_idx
u_forest_size
p_forest_string_char
Returns
char
Definition at line 194 of file forest_utils.c.
 {
     char u_neighbor_val;
     if((u_cell_idx % u_forest_size) == (u_forest_size - 1))
     {
         u_neighbor_val = 0;
     }
     else
     {
         u_neighbor_val = p_forest_string_char[u_cell_idx+1];
     }
     return u_neighbor_val;
 }
Referenced by modify_cell().
update_forest_status()
errors_e update_forest_status (char * p_forest_string_char, const uint32_t u_forest_size)
update_forest_status takes the current forest state and updates it –inplace– according to the following logic:
All trees near Fire, are turning to Fire
All ground cells with atleast two neighboring cells (INCLUDING DIAGNALS) are turning to Tree
All fires becomes Ground
example: size = 3, T G F T G T G F T
==> T T G T T F G G F
Parameters
p_forest_string_char string representing the forest - hold 'F','G','T' charecters and ends with '\0'
u_forest_size size of the forest.
Returns
errors_e status of the function, 0 for success and ERROR codes otherwise
Definition at line 40 of file forest_utils.c.
 {
     debug_print("Entered function: update_forest_status\n");
     debug_print("Forest state before updating:\n");
     debug_forest_print(p_forest_string_char, u_forest_size);
     errors_e e_status = ERROR_OK;
     const uint32_t NUM_OF_FOREST_CELLS = u_forest_size * u_forest_size;
     const uint32_t _size_in_bytes = (NUM_OF_FOREST_CELLS + 1) * sizeof(char);
     char *p_backup_forest_string = (char*)malloc((NUM_OF_FOREST_CELLS + 1) * sizeof(char));
     if(p_backup_forest_string)
     {
         strcpy_s(p_backup_forest_string, _size_in_bytes, p_forest_string_char);
         // Iterate oover all the cells in the forest and update their value
         for(uint32_t u_cell_idx = 0; u_cell_idx < NUM_OF_FOREST_CELLS; u_cell_idx++)
         {
             // Assiging to a new variable for debugability: easier to see the returned value.
             const char u_new_cell_value = modify_cell(u_cell_idx, u_forest_size, p_backup_forest_string);
             p_forest_string_char[u_cell_idx] = u_new_cell_value;
         }
         free(p_backup_forest_string);
         p_backup_forest_string = NULL;
     }
     else
     {
         e_status = ERROR_FAILED_TO_ALLOCATE_MEMORY_E;
     }
     debug_print("Forest state after updating:\n");
     debug_forest_print(p_forest_string_char, u_forest_size);
     return e_status;
 }
References debug_forest_print(), debug_print, ERROR_FAILED_TO_ALLOCATE_MEMORY_E, ERROR_OK, and modify_cell().
Referenced by main().
upper_left_neighbor()
static char upper_left_neighbor (const uint32_t u_cell_idx, const uint32_t u_forest_size, const char * p_forest_string_char) static
Parameters
u_cell_idx
u_forest_size
p_forest_string_char
Returns
char
Definition at line 264 of file forest_utils.c.
 {
     char u_neighbor_val;
     if((u_cell_idx < u_forest_size) || ((u_cell_idx % u_forest_size) == 0))
     {
         u_neighbor_val = 0;
     }
     else
     {
         u_neighbor_val = p_forest_string_char[u_cell_idx - u_forest_size - 1];
     }
     return u_neighbor_val;
 }
Referenced by modify_cell().
upper_neighbor()
static char upper_neighbor (const uint32_t u_cell_idx, const uint32_t u_forest_size, const char * p_forest_string_char) static
upper_neighbor returns the value of the upper neighbor in a given forest string. If the cell has no such neighbors, i.e. it is the upper most row of the tree, returns a value of 0.
Parameters
u_cell_idx
u_forest_size
p_forest_string_char
Returns
char
Definition at line 218 of file forest_utils.c.
 {
     char u_neighbor_val;
     if(u_cell_idx < u_forest_size)
     {
         u_neighbor_val = 0;
     }
     else
     {
         u_neighbor_val = p_forest_string_char[u_cell_idx - u_forest_size];
     }
     return u_neighbor_val;
 }
Referenced by modify_cell().
upper_right_neighbor()
static char upper_right_neighbor (const uint32_t u_cell_idx, const uint32_t u_forest_size, const char * p_forest_string_char) static
Parameters
u_cell_idx
u_forest_size
p_forest_string_char
Returns
char
Definition at line 286 of file forest_utils.c.
 {
     char u_neighbor_val;
     if((u_cell_idx < u_forest_size) || ((u_cell_idx % u_forest_size) == (u_forest_size - 1)))
     {
         u_neighbor_val = 0;
     }
     else
     {
         u_neighbor_val = p_forest_string_char[u_cell_idx - u_forest_size + 1];
     }
     return u_neighbor_val;
 }
Referenced by modify_cell().